Use 'file1.txt' in workflow

diff --git a/.github/workflows/runOnPullRequest.yml b/.github/workflows/runOnPullRequest.yml
--- a/.github/workflows/runOnPullRequest.yml
+++ b/.github/workflows/runOnPullRequest.yml
@@ -18,10 +18,4 @@ jobs:
 
       # Runs a single command using the runners shell
       - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+        run: findstr /c:"Hello World" file1.txt >nul || (echo "Hello World" was not found in file1.txt && exit 1)
